# Lab 2 

# Introduction to NumPy

In this lab, you'll be working through Chapter 2 to get an introduction to the numerical computing package for Python, NumPy. This notebook is made up of two sections.

- Section 1: Work through the code samples in Chapter 2
- Section 2: Exercises

# Section 1: Code Practice

In this section, you will be reading through the various chapter sections and typing out/running the code samples given in the sections. The purpose of this is for you to practice using Jupyter to run Python code as well as learn about the functionality available to you in both IPython and Jupyter.

##### Executing code in Jupyter

When typing and executing code in Jupyter, it is helpful to know the various keyboard shortcuts. You can find the full list of these by clicking **Help &rarr; Keyboard Shortcuts** in the menu. However, the two most useful keyboard shortcuts are:

- `Shift-Enter`: Execute the current cell and advance to the next cell. This will create one if none exists, but if a cell exists below your current cell, a new cell will **not** be created.
- `Alt-Enter`: Execute the current cell and **create** a new cell below.
- `Control-Enter`: Execute the current cell without advancing to the next cell

When writing your code, you will be using these two commands to make sure input/output (`In`/`Out`) is consistent with what is found in the chapter. If you create a cell by mistake, you can always go to **Edit &rarr; Delete Cells** to remove it.

#### Purpose of Section 1

Your purpose in this section is 

- **Type out** the code examples from the chapter (do not copy and paste)
- **Run** them
- **Check** to **make sure** you are getting the same results as what is contained in the chapter

---




## Understanding Data Types in Python

#### A Python List is More Than Just a List

In [ ]:
L = list(range(10))
L

In [ ]:
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
type(L[0])

#### Fixed-Type Arrays in Python

In [ ]:
import array
L = list(range(10))
A = array.array('i', L)
A

In [ ]:
array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Creating Arrays from Python Lists

In [2]:
# integer array: 
np.array([1, 4, 2, 5, 3])

NameError: name 'np' is not defined

In [ ]:
array([1, 4, 2, 5, 3])

In [ ]:
np.array([3.14, 4, 2, 3])

In [1]:
array([3.14, 4, , 2, 3. ])

SyntaxError: invalid syntax (2831132110.py, line 1)

#### Creating Arrays from Scratch

In [ ]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

In [ ]:
array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
# Create a 3x5 floating-point array filled with ones
np.ones((3, 5), dtype=float)

In [ ]:
array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [ ]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

In [ ]:
array([[ 3.14,  3.14,  3.14,  3.14,  3.14],
       [ 3.14,  3.14,  3.14,  3.14,  3.14],
       [ 3.14,  3.14,  3.14,  3.14,  3.14]])

In [ ]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)

In [ ]:
array([[ 0.99844933,  0.52183819,  0.22421193],
       [ 0.08007488,  0.45429293,  0.20941444],
       [ 0.14360941,  0.96910973,  0.946117  ]])

In [ ]:
array([[ 1.51772646,  0.39614948, -0.10634696],
       [ 0.25671348,  0.00732722,  0.37783601],
       [ 0.68446945,  0.15926039, -0.70744073]])
# Create a 3x3 array of ra

In [ ]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

## The Basics of NumPy Arrays

### NumPy Array Attributes

In [ ]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [ ]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

In [ ]:
print("dtype:", x3.dtype)

In [ ]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

### Array Indexing: Accessing Single Elements

In [ ]:
x1

In [ ]:
array([5, 0, 3, 3, 7, 9])

In [ ]:
x1[0]

In [ ]:
5

In [ ]:
x1[4]

In [ ]:
7

In [ ]:
x1[-1]

In [ ]:
9

In [ ]:
x[-2]

In [ ]:
7

### Array Slicing: Accessing Subarrays

#### One-dimensional subarrays

In [ ]:
x = np.arange(10)
x

In [ ]:

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x[:5]  # first five elements

In [ ]:
array([0, 1, 2, 3, 4])

In [ ]:
array([5, 6, 7, 8, 9])

In [ ]:
array([4, 5, 6])

In [ ]:
x[1::2]  # every other element, starting at index 1

In [ ]:
array([1, 3, 5, 7, 9])

#### Multi-dimentional subarrays

In [ ]:
x2

In [ ]:
array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [ ]:
array([[12,  5,  2],
       [ 7,  6,  8]]

In [ ]:
array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [ ]:
x2[::-1, ::-1]

In [ ]:
array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])


#### Subarrays as no-copy views

In [ ]:
print(x2[:, 0])  # first column of x2

In [ ]:
print(x2[0, :])  # first row of x2

In [ ]:
print(x2[0])  # equivalent to x2[0, :]

#### Creating copies of arrays

In [ ]:
print(x2)

In [ ]:
x2_sub = x2[:2, :2]
print(x2_sub)

In [ ]:
x2_sub[0, 0] = 99
print(x2_sub)

### Reshaping of Arrays

In [ ]:
x = np.array([1, 2, 3])

# row vector via reshape
x.reshape((1, 3))

In [ ]:
array([[1, 2, 3]])

In [ ]:
# row vector via newaxis
x[np.newaxis, :]

In [ ]:
array([[1],
       [2],
       [3]])

### Array Concatenation and Splitting

#### Concatenation of arrays

In [ ]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

In [ ]:
array([1, 2, 3, 3, 2, 1])

In [ ]:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

In [ ]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [ ]:
# concatenate along the first axis
np.concatenate([grid, grid])

In [ ]:
array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

#### Splitting of arrays

In [ ]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

In [ ]:
grid = np.arange(16).reshape((4, 4))
grid

In [ ]:
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

## Computation on NumPy Arrays: Universal Functions

### The Slowness of Loops

In [ ]:
import numpy as np
np.random.seed(0)

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output
        
values = np.random.randint(1, 10, size=5)
compute_reciprocals(values)

In [ ]:
big_array = np.random.randint(1, 100, size=1000000)
%timeit compute_reciprocals(big_array)

### Introducing UFuncs

In [ ]:
print(compute_reciprocals(values))
print(1.0 / values)

In [ ]:
%timeit (1.0 / big_array)

In [ ]:
np.arange(5) / np.arange(1, 6)

In [ ]:
x = np.arange(9).reshape((3, 3))
2 ** x

### Exploring NumPy's UFuncs

#### Array arithmetic

In [ ]:
x = np.arange(4)
print("x      =", x)
print("x + 5  =", x + 5)
print("x - 5  =", x - 5)
print("x * 2  =", x * 2)
print("x / 2  =", x / 2)
print("x // 2 =", x // 2)  # floor division

In [ ]:
x = np.arange(4)
print("x      =", x)
print("x + 5  =", x + 5)
print("x - 5  =", x - 5)
print("x * 2  =", x * 2)
print("x / 2  =", x / 2)
print("x // 2 =", x // 2)  # floor division

In [ ]:
-(0.5*x + 1) ** 2

In [ ]:
np.add(x, 2)

#### Absolute value

In [ ]:
x = np.array([-2, -1, 0, 1, 2])
abs(x)

In [ ]:
np.absolute(x)


In [ ]:
np.abs(x)

In [ ]:
x = np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j])
np.abs(x)

#### Trigonometric functions

In [ ]:
theta = np.linspace(0, np.pi, 3)

In [ ]:
print("theta      = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

In [ ]:
x = [-1, 0, 1]
print("x         = ", x)
print("arcsin(x) = ", np.arcsin(x))
print("arccos(x) = ", np.arccos(x))
print("arctan(x) = ", np.arctan(x))

#### Exponents and logarithms

In [ ]:
x = [1, 2, 3]
print("x     =", x)
print("e^x   =", np.exp(x))
print("2^x   =", np.exp2(x))
print("3^x   =", np.power(3, x))

In [ ]:
x = [1, 2, 4, 10]
print("x        =", x)
print("ln(x)    =", np.log(x))
print("log2(x)  =", np.log2(x))
print("log10(x) =", np.log10(x))

In [ ]:
x = [0, 0.001, 0.01, 0.1]
print("exp(x) - 1 =", np.expm1(x))
print("log(1 + x) =", np.log1p(x))

#### Specialized ufuncs

In [ ]:
from scipy import special

In [ ]:
# Gamma functions (generalized factorials) and related functions
x = [1, 5, 10]
print("gamma(x)     =", special.gamma(x))
print("ln|gamma(x)| =", special.gammaln(x))
print("beta(x, 2)   =", special.beta(x, 2))

In [ ]:
# Error function (integral of Gaussian)
# its complement, and its inverse
x = np.array([0, 0.3, 0.7, 1.0])
print("erf(x)  =", special.erf(x))
print("erfc(x) =", special.erfc(x))
print("erfinv(x) =", special.erfinv(x))

### Advanced UFunc Features

#### Specifying output

In [ ]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)
print(y)

In [ ]:
y = np.zeros(10)
np.power(2, x, out=y[::2])
print(y)

#### Aggregates

In [ ]:
x = np.arange(1, 6)
np.add.reduce(x)


In [ ]:
np.multiply.reduce(x)

In [ ]:
np.add.accumulate(x)

In [ ]:
np.multiply.accumulate(x)

#### Outer products

In [ ]:
x = np.arange(1, 6)
np.multiply.outer(x, x)

## Aggregations: Min, Max, and Everything In Between

### Summing the Values in an Array

In [ ]:
import numpy as np

In [ ]:
L = np.random.random(100)
sum(L)

In [ ]:
np.sum(L)

In [ ]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

### Minimum and Maximum

In [ ]:
min(big_array), max(big_array)

In [ ]:
np.min(big_array), np.max(big_array)

In [ ]:
%timeit min(big_array)
%timeit np.min(big_array)

In [ ]:
print(big_array.min(), big_array.max(), big_array.sum())

#### Multi dimensional aggregates

In [ ]:
M = np.random.random((3, 4))
print(M)

In [ ]:
M.sum()


In [ ]:
M.min(axis=0)

In [ ]:
M.max(axis=1)


### Example: What is the Average Height of US Presidents?

For this section, you'll need to execute the following cell first. 

In [ ]:
def array_from_url(url, column):
    import pandas as pd
    import numpy as np
    data = pd.read_csv(url)
    return np.array(data[column])

heights = array_from_url('https://raw.githubusercontent.com/jakevdp/PythonDataScienceHandbook/8a34a4f653bdbdc01415a94dc20d4e9b97438965/notebooks/data/president_heights.csv','height(cm)')
print(heights)

For this portion, start with the cell labeled `In [15]:`

In [ ]:
!head -4 data/president_heights.csv

In [ ]:
import pandas as pd
data = pd.read_csv('data/president_heights.csv')
heights = np.array(data['height(cm)'])
print(heights)

In [ ]:
print("Mean height:       ", heights.mean())
print("Standard deviation:", heights.std())
print("Minimum height:    ", heights.min())
print("Maximum height:    ", heights.max())

In [ ]:
print("25th percentile:   ", np.percentile(heights, 25))
print("Median:            ", np.median(heights))
print("75th percentile:   ", np.percentile(heights, 75))

---

# Section 2: Exercises

In this section, you will be provided a few exercises to demonstrate your understanding of the chapter contents. Each exercise will have a Markdown section describing the problem, and you will provide cells below the description with code, comments and visual demonstrations of your solution.

---

### Problem 1

Make sure you have the `array_from_url` function defined:

```python
def array_from_url(url, column):
    import pandas as pd
    import numpy as np
    data = pd.read_csv(url)
    return np.array(data[column])
```

Using the `array_from_url` function, use the following arguments

- URL: `"https://raw.githubusercontent.com/jakevdp/data-USstates/master/state-areas.csv"`
- column: `"area (sq. mi)"`

to load the NumPy array into a variable `areas`.

Print out the `mean` area for all the states in the US. Use built-in methods and UFuncs where appropriate.

In [ ]:
import numpy as np

areas = array_from_url("https://raw.githubusercontent.com/jakevdp/data-USstates/master/state-areas.csv", "area (sq. mi)")
mean_area = np.mean(areas)
print(mean_area)


---

### Problem 2

Using the `areas` array created above, assign the total area of the United States and D.C. to a new variable, `total_area` by using the `sum` method of `areas`.

In [ ]:
total_area = np.sum(areas)


---

### Problem 3

Using NumPy's various UFuncs, create a new array, `area_percentage`, that is each state's area as percentage of the `total_area`.

E.g. Given that Alaska's area is the second element of the array `areas` (i.e. `areas[1]`), Alaska's percentage of the total would be: `areas[1]/total_area`

In [ ]:
area_percentage = 100 * (areas / total_area)


### Problem 4

Print out the heights of the American Presidents in feet (rather than cm). Use UFuncs for this. You'll need to look up the formula to convert cm to feet.

In [ ]:
print(heights_cm / 30.48)
